# <font color=#4FB7C9>NumPy</font>


## Basics
___
***Contents:***
- Placeholders

In [1]:
import numpy as np

<font color=#CA7747>**np.array(Iteratable)**</font> $\Rightarrow$ Creates a 1D or multi-dimentional array depending on the parameter.

<font color=#CA7747>**np.arange(Start, End, Step)**</font> $\Rightarrow$ Creats a ranged array starting from start till end with step.

In [2]:
print("1.", np.array((1,2,3)))
print("2.", np.array([(1,2,3),(4,5,6),(7,8,9)]).tolist())
print("3.", np.arange(1, 10, 2))

1. [1 2 3]
2. [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
3. [1 3 5 7 9]


### Placeholders:

<font color=#CA7747>**np.linspace(Start, End, Divisions)**</font> $\Rightarrow$ Divide equally the interval between start and end.

<font color=#CA7747>**np.zeros((Row, Column))**</font> $\Rightarrow$ Creats an array filled with zeros.

<font color=#CA7747>**np.ones((Row, Column))**</font> $\Rightarrow$ Creats an array filed with ones.

<font color=#CA7747>**np.random.random((Row, Column))**</font> $\Rightarrow$ Creats a random array.

<font color=#CA7747>**np.random.empty((Row, Column))**</font> $\Rightarrow$ Creats a emepty array.

In [3]:
print(f"1. {np.linspace(1,5,6)} \t\tID: {id(np.linspace(1,5,6))}")
print(f"2. {np.zeros((2,2)).tolist()} \t\tID: {id(np.zeros((2,2)).tolist())}") #tolist converts array to a list , just to print in a single line
print(f"3. {np.ones((2,2)).tolist()} \t\tID: {id(np.ones((2,2)).tolist())}")
print(f"4. {np.around(np.random.random((2, 2)), 3).tolist()} \tID: {id(np.around(np.random.random((2,2)), 3).tolist())}") #around to round off till 3rd decimals
print(f"5. {np.around(np.empty((2, 2)), 3).tolist()} \tID: {id(np.around(np.empty((2,2)), 3).tolist())}")

1. [1.  1.8 2.6 3.4 4.2 5. ] 		ID: 2473248103040
2. [[0.0, 0.0], [0.0, 0.0]] 		ID: 2473248170120
3. [[1.0, 1.0], [1.0, 1.0]] 		ID: 2473244361096
4. [[0.898, 0.775], [0.21, 0.185]] 	ID: 2473248170120
5. [[0.963, 0.834], [0.976, 0.832]] 	ID: 2473243211464


## ARRAY
___

***Contents:***
- Array Properties
- Copying and Sorting




### Array Properties:

<font color=#CA7747>**array.shape**</font> $\Rightarrow$ Dimensions (Rows, Columns)

<font color=#CA7747>**len(array)**</font> $\Rightarrow$ Length of the array

<font color=#CA7747>**array.ndim**</font> $\Rightarrow$ Number of dimentions

<font color=#CA7747>**array.size**</font> $\Rightarrow$ Number of array elements

<font color=#CA7747>**array.dtype**</font> $\Rightarrow$ Data Type

<font color=#CA7747>**array.astype(type)**</font> $\Rightarrow$ Convert to Data Type

<font color=#CA7747>**type(array)**</font> $\Rightarrow$ Data Type


In [4]:
arr = np.random.random((3,3)) * 4
print(f"The array is-> {np.around(arr, 2).tolist()}")
print(f"Array shape is-> {arr.shape}")
print(f"Array lenght is-> {len(arr)}")
print(f"Number of Array dimentions are-> {arr.ndim}")
print(f"Array size is-> {arr.size}")
print(f"Array elements are of type-> {arr.dtype}")
print(f"Array is-> {type(arr)}")
print(f"Converting it from {arr.dtype} to int32-> {arr.astype('int32').tolist()}")

The array is-> [[0.8, 2.62, 1.51], [1.5, 3.43, 1.5], [2.74, 1.21, 1.56]]
Array shape is-> (3, 3)
Array lenght is-> 3
Number of Array dimentions are-> 2
Array size is-> 9
Array elements are of type-> float64
Array is-> <class 'numpy.ndarray'>
Converting it from float64 to int32-> [[0, 2, 1], [1, 3, 1], [2, 1, 1]]


### Copying and Sorting:

<font color=#CA7747>**array.copy()**</font> $\Rightarrow$ Returns a copy of array

<font color=#CA7747>**array.sort(Axis)**</font> $\Rightarrow$ Sort Axis of the array


In [5]:
arr1d = np.random.randint(10, size=5)
print(arr1d, '\n')
arr1d.sort()
print(arr1d, '\n')

[0 2 7 7 3] 

[0 2 3 7 7] 



In [59]:
arr2d = np.random.randint(10, size=(3, 3))


print(arr2d, '\n')
print(9*'-','AFTER SORTING 2D ARRAY',9*'-')
arr2d2 = arr2d.copy()
arr2d.sort(axis=0)
arr2d2.sort(axis=1)
print(arr2d, '\n')
print(arr2d2, '\n')
print(40*('-'), '\n')

[[0 6 0]
 [4 9 8]
 [8 1 9]] 

--------- AFTER SORTING 2D ARRAY ---------
[[0 1 0]
 [4 6 8]
 [8 9 9]] 

[[0 0 6]
 [4 8 9]
 [1 8 9]] 

---------------------------------------- 



In [61]:
arr3d = np.random.randint(10, size=(2, 2, 2))
print(arr3d, '\n')
print(9*'-','AFTER SORTING 3D ARRAY',9*'-')
arr3d1 = arr3d.copy()
arr3d2 = arr3d.copy()
arr3d.sort(axis=0)
arr3d1.sort(axis=1)
arr3d2.sort(axis=2)
print(arr3d, '\n\n')
print(arr3d1, '\n\n')
print(arr3d2, '\n\n')
print(40*('-'), '\n')


[[[1 2]
  [3 2]]

 [[2 7]
  [7 0]]] 

--------- AFTER SORTING 3D ARRAY ---------
[[[1 2]
  [3 0]]

 [[2 7]
  [7 2]]] 


[[[1 2]
  [3 2]]

 [[2 0]
  [7 7]]] 


[[[1 2]
  [2 3]]

 [[2 7]
  [0 7]]] 


---------------------------------------- 

