## Mathematics
___

***Contents:***
- Basic operators
- Trigonometry
- Logarithm
- Dot Product
- Transpose
- Flattening


In [116]:
import numpy as np

In [117]:
a1 = np.random.randint(9, size=4)
a2 = np.random.randint(9, size=4)

print(f"Array 1 = {a1.tolist()}")
print(f"Array 2 = {a2.tolist()}")

Array 1 = [2, 4, 4, 1]
Array 2 = [8, 3, 1, 6]


In [118]:
a21 = np.random.randint(9, size=(2,2))
a22 = np.random.randint(9, size=(2,2))

print(f"Array 1 = {a21.tolist()}")
print(f"Array 2 = {a22.tolist()}")

Array 1 = [[0, 5], [8, 7]]
Array 2 = [[6, 5], [1, 7]]


### Addition:

In [119]:
np.add(a1, a2)

array([10,  7,  5,  7])

In [120]:
a1 + a2 

array([10,  7,  5,  7])

In [121]:
np.add(a21, a22)

array([[ 6, 10],
       [ 9, 14]])

In [122]:
a21 + a22

array([[ 6, 10],
       [ 9, 14]])

In [123]:
np.sum(a1)

11

In [124]:
np.sum(a21)

20

### Subtraction:

In [125]:
np.subtract(a1, a2)

array([-6,  1,  3, -5])

In [126]:
a1 - a2 

array([-6,  1,  3, -5])

In [127]:
np.subtract(a21, a22)

array([[-6,  0],
       [ 7,  0]])

In [128]:
a21 - a22

array([[-6,  0],
       [ 7,  0]])

### Multiplication

In [129]:
np.multiply(a1, a2)

array([16, 12,  4,  6])

In [130]:
a1 * a2

array([16, 12,  4,  6])

In [131]:
np.multiply(a21, a22)   # It's element wise multiplication

array([[ 0, 25],
       [ 8, 49]])

In [132]:
a21 * a22

array([[ 0, 25],
       [ 8, 49]])

In [133]:
np.multiply(a22, 2)   # It's element wise multiplication

array([[12, 10],
       [ 2, 14]])

In [134]:
a22 * 2

array([[12, 10],
       [ 2, 14]])

### Division

In [135]:
np.divide(a1, a2)

array([0.25      , 1.33333333, 4.        , 0.16666667])

In [136]:
a1 / a2 

array([0.25      , 1.33333333, 4.        , 0.16666667])

In [137]:
(a1 + 1) / (a2 + 1)   # Making sure that divison by zero error doesn't occure since a1 and a2 are randomly generated

array([0.33333333, 1.25      , 2.5       , 0.28571429])

In [138]:
a21 / 2

array([[0. , 2.5],
       [4. , 3.5]])

In [139]:
a21 / a22 

array([[0., 1.],
       [8., 1.]])

### Square Root

In [140]:
np.sqrt(a1)

array([1.41421356, 2.        , 2.        , 1.        ])

### Trigonometry

In [141]:
np.sin(a1) # Element wise

array([ 0.90929743, -0.7568025 , -0.7568025 ,  0.84147098])

In [142]:
np.sin(a21)

array([[ 0.        , -0.95892427],
       [ 0.98935825,  0.6569866 ]])

In [143]:
np.cos(a1)

array([-0.41614684, -0.65364362, -0.65364362,  0.54030231])

In [144]:
np.cos(a21)

array([[ 1.        ,  0.28366219],
       [-0.14550003,  0.75390225]])

In [145]:
np.tan(a1)

array([-2.18503986,  1.15782128,  1.15782128,  1.55740772])

In [146]:
np.sin(a1) / np.cos(a1)

array([-2.18503986,  1.15782128,  1.15782128,  1.55740772])

In [147]:
np.tan(a21)

array([[ 0.        , -3.38051501],
       [-6.79971146,  0.87144798]])

In [148]:
np.sin(a21) / np.cos(a21)

array([[ 0.        , -3.38051501],
       [-6.79971146,  0.87144798]])

### Logarithm

In [149]:
np.log(a1)

array([0.69314718, 1.38629436, 1.38629436, 0.        ])

In [150]:
np.log(a21)

C:\Python\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[      -inf, 1.60943791],
       [2.07944154, 1.94591015]])

### Dot Product

In [151]:
np.dot(a1, a2)

38

In [152]:
np.sum(a1 * a2)

38

### Transpose

In [153]:
if len(a1.shape) == 1:
    a1 = a1.reshape(1, a1.shape[0]) # Changing shape of a1 from (4,) to (4, 1) if a1 has only one dimension

np.transpose(a1)

array([[2],
       [4],
       [4],
       [1]])

In [154]:
if len(a1.shape) == 1:
    a1 = a1.reshape(1, a1.shape[0]) # Changing shape of a1 from (4,) to (4, 1) if a1 has only one dimension

a1.T

array([[2],
       [4],
       [4],
       [1]])

In [155]:
a21

array([[0, 5],
       [8, 7]])

In [156]:
a21.T

array([[0, 8],
       [5, 7]])

### Flattening

In [157]:
a21.flatten()

array([0, 5, 8, 7])

In [158]:
a21.T.flatten()

array([0, 8, 5, 7])